const products=[
{id:'shawarma',name:'Шаурма',category:'Горячее',group:'hot',price:'250 ₽',description:'Сочная курица, хрустящий айсберг, свежий томат и солёный огурец под чесночным соусом. Сытно, свежо и без лишнего.',ingredients:'Курица · айсберг · томат · солёный огурец · чесночный соус',shape:'wrap',color:'#f3cd62',tag:'Сытный хит'},
{id:'doner',name:'Донер',category:'Горячее',group:'hot',price:'250 ₽',description:'Курица, свежие овощи, солёный огурец и чесночный соус. Простой и сытный вариант на каждый день.',ingredients:'Курица · айсберг · томат · солёный огурец · чесночный соус',shape:'wrap',color:'#91b9be',tag:'На каждый день'},
{id:'kebab',name:'Куриный кебаб',category:'Горячее',group:'hot',price:'Цена уточняется',description:'Куриный кебаб с салатом, томатным соусом и гарниром на выбор.',ingredients:'Куриный кебаб · салат · гарнир на выбор · томатный соус. Гарнир: рис или гречка.',shape:'kebab',color:'#f1a37a',tag:'Горячее'},
{id:'banana',name:'Банан + шоколад',category:'Блины',group:'blini',price:'200 ₽',description:'Горячий блин со сладким бананом и шоколадным соусом.',ingredients:'Банан · шоколадный соус',shape:'pancake',color:'#edc5d1',tag:'Сладкий блин'},
{id:'apple',name:'Яблоко + карамель',category:'Блины',group:'blini',price:'200 ₽',description:'Тёплое карамелизированное яблоко, карамель и корица в горячем блине.',ingredients:'Карамелизированное яблоко · карамельный соус · корица',shape:'pancake',color:'#edb357',tag:'Сладкий блин'},
{id:'classic',name:'Классический блин',category:'Блины',group:'blini',price:'75 ₽',description:'Тонкий, свежий и горячий. Хорош сам по себе или с любимой добавкой.',ingredients:'Добавки уточняйте в точке.',shape:'blin',color:'#f5da83',tag:'Основа'},
{id:'potato',name:'Картошка + яйцо',category:'Блины',group:'blini',price:'250 ₽',description:'Сытный блин с картошкой и яйцом.',ingredients:'Картошка · яйцо',shape:'blin',color:'#d4df9b',tag:'Сытный блин'},
{id:'ham',name:'Ветчина + сыр',category:'Блины',group:'blini',price:'290 ₽',description:'Горячий блин с ветчиной и сыром.',ingredients:'Ветчина · сыр',shape:'blin',color:'#f2ac8b',tag:'Сытный блин'},
{id:'mexican',name:'Мексиканский',category:'Блины',group:'blini',price:'350 ₽',description:'Позиция из меню ТИХО. Состав уточняется.',ingredients:'Состав уточняется.',shape:'blin',color:'#f28c59',tag:'Пикантный'},
{id:'chicken',name:'Сочная курица',category:'Блины',group:'blini',price:'330 ₽',description:'Горячий блин с курицей.',ingredients:'Курица. Другие ингредиенты уточняются.',shape:'blin',color:'#a5bfd5',tag:'Сытный блин'},
{id:'baklava',name:'Пахлава',category:'Десерты',group:'sweet',price:'300 ₽',description:'Свежая пахлава — один из ключевых продуктов ТИХО.',ingredients:'Состав и порция уточняются.',shape:'baklava',color:'#e8b654',tag:'Герой ТИХО'}
];
const grid=document.querySelector('#product-grid'),favorites=new Set(JSON.parse(localStorage.getItem('tiho-likes')||'[]'));let current=null,angle=0,toastTimer;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function card(p){return `<article class="product-card" data-id="${p.id}" tabindex="0" aria-label="Открыть ${esc(p.name)}"><div class="card-visual" style="--card-bg:${p.color}"><span class="card-tag">${esc(p.tag)}</span><button class="like ${favorites.has(p.id)?'on':''}" aria-label="${favorites.has(p.id)?'Убрать из любимого':'Добавить в любимое'}" data-like="${p.id}">${favorites.has(p.id)?'♥':'♡'}</button><div class="food-shape ${p.shape}"></div></div><div class="card-info"><div class="card-info-top"><h3>${esc(p.name)}</h3><span class="card-price">${esc(p.price)}</span></div><p>${esc(p.description)}</p><span class="card-open">Подробнее ↗</span></div></article>`}
function render(filter='all'){grid.innerHTML=products.filter(p=>filter==='all'||p.group===filter).map(card).join('')}
function updateLikes(){localStorage.setItem('tiho-likes',JSON.stringify([...favorites]));render(document.querySelector('.filter.active')?.dataset.filter||'all')}
function showToast(s){let t=document.querySelector('.toast');t.textContent=s;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2100)}
document.querySelector('.filters').addEventListener('click',e=>{let b=e.target.closest('[data-filter]');if(!b)return;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render(b.dataset.filter)});
grid.addEventListener('click',e=>{let l=e.target.closest('[data-like]');if(l){e.stopPropagation();let id=l.dataset.like;favorites.has(id)?favorites.delete(id):favorites.add(id);updateLikes();return}let c=e.target.closest('.product-card');if(c)openProduct(c.dataset.id)});
grid.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.product-card')){e.preventDefault();openProduct(e.target.dataset.id)}});
const pd=document.querySelector('#product-dialog');function openProduct(id){current=products.find(p=>p.id===id);angle=0;document.querySelector('.dialog-media').innerHTML=`<div class="food-shape ${current.shape}" style="--card-bg:${current.color}"></div>`;document.querySelector('.dialog-category').textContent=current.category;document.querySelector('.dialog-title').textContent=current.name;document.querySelector('.dialog-price').textContent=current.price;document.querySelector('.dialog-description').textContent=current.description;document.querySelector('.dialog-ingredients').textContent=current.ingredients;let l=document.querySelector('.large-like');l.innerHTML=`${favorites.has(id)?'♥':'♡'} <span>${favorites.has(id)?'В любимом':'Нравится'}</span>`;l.classList.toggle('on',favorites.has(id));pd.showModal()}
pd.querySelector('.dialog-close').onclick=()=>pd.close();pd.addEventListener('click',e=>{if(e.target===pd)pd.close()});document.querySelector('.large-like').onclick=()=>{favorites.has(current.id)?favorites.delete(current.id):favorites.add(current.id);updateLikes();openProduct(current.id)};
function rotate(dir){angle+=dir*24;document.querySelector('.dialog-media .food-shape').style.transform=`scale(1.7) rotate(${angle}deg)`}document.querySelector('.gallery-prev').onclick=()=>rotate(-1);document.querySelector('.gallery-next').onclick=()=>rotate(1);
let sx=0,sy=0,dragging=false,media=document.querySelector('.dialog-media');media.addEventListener('pointerdown',e=>{if(!e.target.closest('.food-shape'))return;sx=e.clientX;sy=e.clientY;dragging=true;media.setPointerCapture(e.pointerId)});media.addEventListener('pointerup',e=>{if(!dragging)return;dragging=false;let dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)>18)rotate(dx>0?1:-1);else if(Math.abs(dy)<8)rotate(1)});
const legal={privacy:['Политика конфиденциальности','<p><b>Оператор:</b> [указать полное наименование / ФИО ИП, адрес и контакты].</p><p>На этой версии сайта нет форм заказа, оплаты, подписки или регистрации. Технически сайт может получать стандартные журналы запросов на стороне хостинга (например, IP-адрес, время, сведения о браузере) для доставки страниц и защиты от сбоев. Лайки товаров хранятся только в localStorage браузера посетителя и никуда не отправляются.</p><p>Внешние системы аналитики, рекламные пиксели и сторонние cookie не подключены. Если они появятся, цели, состав данных, получателей и сроки хранения необходимо описать здесь до подключения.</p><p>Обращения по вопросам данных: [контакт оператора]. Сроки хранения и порядок удаления: [заполнить по фактическим процессам].</p>'],consent:['Согласие на обработку данных','<p>Сейчас сайт не запрашивает персональные данные через формы и не отправляет лайки оператору. Отдельное согласие в интерфейсе этой версии не собирается.</p><p>Если появятся формы, перед запуском нужно описать конкретную цель, перечень данных, действия с ними, срок обработки, порядок отзыва и получателей. Согласие должно быть оформлено отдельно от иных документов и даваться активным действием пользователя, если закон требует согласия.</p><p>Оператор и контакт для отзыва: [заполнить].</p>'],operator:['Сведения об операторе','<p><b>Наименование / ФИО:</b> [заполнить]</p><p><b>ОГРН / ОГРНИП и ИНН:</b> [заполнить]</p><p><b>Адрес места нахождения:</b> [заполнить]</p><p><b>Контакт для обращений по персональным данным:</b> [заполнить]</p><p>Если каталог будет использоваться для дистанционной продажи, до заключения договора необходимо разместить сведения продавца и полную достоверную информацию о товаре в объёме, предусмотренном законодательством о защите прав потребителей.</p>'],cookies:['Cookie и статистика','<p>В этой версии нет сторонних cookie, веб-аналитики, рекламных пикселей и встроенных карт. Избранные товары запоминаются в localStorage только на устройстве пользователя; это не отправляется владельцу сайта.</p><p>Хостинг может вести технические журналы запросов. Уточните у выбранного хостинг-провайдера, какие данные он фиксирует, где они хранятся и сколько сохраняются, и внесите сведения в политику.</p><p>При подключении аналитики сначала оцените её настройки, правовое основание, передачу данных и необходимость уведомления/согласия. Не устанавливайте необязательные трекеры до соответствующей настройки.</p>']};
const ld=document.querySelector('#legal-dialog');document.querySelector('.footer-bottom').addEventListener('click',e=>{let b=e.target.closest('[data-legal]');if(!b)return;let [title,body]=legal[b.dataset.legal];ld.querySelector('h2').textContent=title;ld.querySelector('.legal-copy').innerHTML=body;ld.showModal()});ld.querySelector('.dialog-close').onclick=()=>ld.close();ld.addEventListener('click',e=>{if(e.target===ld)ld.close()});render();
